name: Build Binaries

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: '1.14'
      - name: Run Cross-build
        run: ./crossbuild.sh
      - name: Show MemGator CLI Help
        run: /tmp/mgbins/memgator-linux-amd64
      - name: Upload Built MemGator Binaries
        uses: actions/upload-artifact@master
        with:
          name: memgator-bins
          path: /tmp/mgbins
